substitutions:
  name: AlexaESP
  external_components_source: github://creepystefan/ESPHOME-Alexa@main
  
external_components:
  - source: ${external_components_source}
    refresh: 0s


esphome:
  name: ALEXAESP
  friendly_name: AlexaESP
  includes:
    - test.h
    
esp8266:
  board: esp8285

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret apixywfpow

ota:
  password: !secret otaxywfpow

web_server:
  port: 9005

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret xywfpow_IP
    gateway: !secret gateway
    subnet: !secret subnet
 
captive_portal:

switch:
  - platform: gpio
    pin: GPIO2
    inverted: true
    name: "GPIO2 LED inverted"
 
